name: Build CUDA Jupyter Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # CUDA 11.8
          - cuda_version: '11.8.0'
            ubuntu_version: '22.04'
          # CUDA 12.1
          - cuda_version: '12.1.1'
            ubuntu_version: '22.04'
          # CUDA 12.4
          - cuda_version: '12.4.1'
            ubuntu_version: '22.04'
          # CUDA 12.6
          - cuda_version: '12.6.1'
            ubuntu_version: '22.04'
          - cuda_version: '12.6.1'
            ubuntu_version: '24.04'
        python_version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/cuda-jupyter:${{ matrix.cuda_version }}-ubuntu${{ matrix.ubuntu_version }}-python${{ matrix.python_version }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
            PYTHON_VERSION=${{ matrix.python_version }}